services:
  middleware:
    image: streamer-bot-middleware:dev
    build:
      dockerfile: src/Software/Middleware/Dockerfile
    ports:
      - "5000:8080"
  frontend:
    image: streamer-bot-frontend:dev
    build:
      context: src/Software/Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    