apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-discord
  labels:
    organization: saveapis
    project: streamer.event-cloud
    app: event-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      organization: saveapis
      project: streamer.event-cloud
      app: event-discord
  template:
    metadata:
      name: event-discord
      labels:
        organization: saveapis
        project: streamer.event-cloud
        app: event-discord
    spec:
      initContainers:
        - name: wait-for-middleware
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z -v -w30 middleware.streamer-bot-cloud-%ENVIRONMENT%.svc.cluster.local 8080; do echo "Waiting for middleware..."; sleep 5; done;' ]
      containers:
        - name: event-discord
          image: registry.digitalocean.com/saveapis/streamer-bot-cloud-event-discord:%VERSION%
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: aspnetcore_environment
              valueFrom:
                configMapKeyRef:
                  name: core
                  key: environment
                  optional: false
            - name: Hangfire__Redis__Host
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: host
                  optional: false
            - name: Hangfire__Redis__Port
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: port
                  optional: false
            - name: Hangfire__Redis__UserName
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: username
                  optional: false
            - name: Hangfire__Redis__Password
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: password
                  optional: false
            - name: Hangfire__Redis__UseSsl
              value: "true"
            - name: Hangfire__Redis__Prefix
              value: "%ENVIRONMENT%:hangfire:event:discord:"
            - name: Hangfire__Dashboard__PrefixPath
              value: "/api/event/discord"
            - name: Encryption__Key
              valueFrom:
                secretKeyRef:
                  name: encryption
                  key: event-discord
                  optional: false
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: event-discord-issuer-audience
                  optional: false
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: event-discord-issuer-audience
                  optional: false
            - name: Jwt__SigningKey
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: event-discord-signing-key
                  optional: false
            - name: Jwt__ExpirationMinutes
              value: "60"

            - name: Logging__BetterStack__Host
              valueFrom:
                secretKeyRef:
                  name: betterstack
                  key: host
                  optional: false
            - name: Logging__BetterStack__Token
              valueFrom:
                secretKeyRef:
                  name: betterstack
                  key: token
                  optional: false
      restartPolicy: Always
      