apiVersion: v1
kind: Service
metadata:
  name: bot-youtube
  labels:
    organization: saveapis
    project: streamer.bot-cloud
    app: bot-youtube
spec:
  selector:
    organization: saveapis
    project: streamer.bot-cloud
    app: bot-youtube
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
