apiVersion: v1
kind: Service
metadata:
  name: middleware
  labels:
    organization: saveapis
    project: streamer.bot-cloud
    app: middleware
spec:
  selector:
    organization: saveapis
    project: streamer.bot-cloud
    app: middleware
    type: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
