// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Software.Middleware.Domains.Common.Persistence.Sql.Context;

#nullable disable

namespace Software.Middleware.Domains.Application.Persistence.Sql.Migrations
{
    [DbContext(typeof(CoreWriteDbContext))]
    [Migration("20250921113411_CreateApplicationScopesTable")]
    partial class CreateApplicationScopesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Core")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Software.Middleware.Domains.Application.Domain.Models.Entities.ApplicationEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AuthSecret")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Key");

                    b.HasIndex("AuthId")
                        .IsUnique();

                    b.HasIndex("AuthSecret")
                        .IsUnique();

                    b.HasIndex("Iv")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Source");

                    b.ToTable("Applications", "Core");
                });

            modelBuilder.Entity("Software.Middleware.Domains.Application.Domain.Models.Entities.ApplicationScopeEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Key");

                    b.ToTable("ApplicationScopes", "Core");
                });
#pragma warning restore 612, 618
        }
    }
}
