apiVersion: v1
kind: Service
metadata:
  name: bot-twitch
  labels:
    organization: saveapis
    project: streamer.bot-cloud
    app: bot-twitch
spec:
  selector:
    organization: saveapis
    project: streamer.bot-cloud
    app: bot-twitch
    type: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
