POST {{baseUrl}}/applications/create
Authorization: ApplicationBasic {{frontendBasicAuth}}
Content-Type: application/json

{
  "key": "test",
  "name": "Test Application",
  "description": "This is a test application",
  "authId": "test_auth_id",
  "authSecret": "dGVzdF9hdXRoX3NlY3JldA=="
}