namespace: streamer-bot-cloud-%ENVIRONMENT%
resources:
  - namespace.yaml
  - ingress.yaml
  - middleware/deployment.yaml
  - middleware/service.yaml
  - event/twitch/deployment.yaml
  - event/twitch/service.yaml
  - event/discord/deployment.yaml
  - event/discord/service.yaml
  - event/youtube/deployment.yaml
  - event/youtube/service.yaml
  - bot/twitch/deployment.yaml
  - bot/twitch/service.yaml
  - bot/discord/deployment.yaml
  - bot/discord/service.yaml
  - bot/youtube/deployment.yaml
  - bot/youtube/service.yaml

configMapGenerator:
  - name: core
    literals:
      - environment=%ENVIRONMENT%

secretGenerator:
  - name: valkey
    literals:
      - host=%VALKEY_HOST%
      - port=%VALKEY_PORT%
      - username=%VALKEY_USERNAME%
      - password=%VALKEY_PASSWORD%
  - name: encryption
    literals:
      - middleware=%ENCRYPTION_MIDDLEWARE_KEY%
      - event-twitch=%ENCRYPTION_EVENT_TWITCH_KEY%
      - event-discord=%ENCRYPTION_EVENT_DISCORD_KEY%
      - event-youtube=%ENCRYPTION_EVENT_YOUTUBE_KEY%
      - bot-twitch=%ENCRYPTION_BOT_TWITCH_KEY%
      - bot-discord=%ENCRYPTION_BOT_DISCORD_KEY%
      - bot-youtube=%ENCRYPTION_BOT_YOUTUBE_KEY%