apiVersion: v1
kind: Service
metadata:
  name: event-twitch
  labels:
    organization: saveapis
    project: streamer.event-cloud
    app: event-twitch
spec:
  selector:
    organization: saveapis
    project: streamer.event-cloud
    app: event-twitch
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
