apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-youtube
  labels:
    organization: saveapis
    project: streamer.event-cloud
    app: event-youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      organization: saveapis
      project: streamer.event-cloud
      app: event-youtube
  template:
    metadata:
      name: event-youtube
      labels:
        organization: saveapis
        project: streamer.event-cloud
        app: event-youtube
    spec:
      initContainers:
        - name: wait-for-middleware
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z -v -w30 middleware.streamer-bot-cloud-%ENVIRONMENT%.svc.cluster.local 8080; do echo "Waiting for middleware..."; sleep 5; done;' ]
      containers:
        - name: event-youtube
          image: registry.digitalocean.com/saveapis/streamer-event-cloud-event-youtube:%VERSION%
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: aspnetcore_environment
              valueFrom:
                configMapKeyRef:
                  name: core
                  key: environment
                  optional: false
      restartPolicy: Always
      