// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Software.Middleware.Domains.Common.Persistence.Sql.Context;

#nullable disable

namespace Software.Middleware.Domains.Common.Persistence.Sql.Migrations
{
    [DbContext(typeof(CoreWriteDbContext))]
    partial class CoreWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Core")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApplicationEntityApplicationScopeEntity", b =>
                {
                    b.Property<string>("ApplicationEntityKey")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ScopesKey")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ApplicationEntityKey", "ScopesKey");

                    b.HasIndex("ScopesKey");

                    b.ToTable("ApplicationApplicationScopes", "Core");
                });

            modelBuilder.Entity("Software.Middleware.Domains.Application.Domain.Models.Entities.ApplicationEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AuthSecret")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Key");

                    b.HasIndex("AuthId")
                        .IsUnique();

                    b.HasIndex("AuthSecret")
                        .IsUnique();

                    b.HasIndex("Iv")
                        .IsUnique();

                    b.HasIndex("State");

                    b.ToTable("Applications", "Core");
                });

            modelBuilder.Entity("Software.Middleware.Domains.Application.Domain.Models.Entities.ApplicationScopeEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Key");

                    b.ToTable("ApplicationScopes", "Core");
                });

            modelBuilder.Entity("ApplicationEntityApplicationScopeEntity", b =>
                {
                    b.HasOne("Software.Middleware.Domains.Application.Domain.Models.Entities.ApplicationEntity", null)
                        .WithMany()
                        .HasForeignKey("ApplicationEntityKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software.Middleware.Domains.Application.Domain.Models.Entities.ApplicationScopeEntity", null)
                        .WithMany()
                        .HasForeignKey("ScopesKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
