apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  labels:
    organization: saveapis
    project: streamer.bot-cloud
    app: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      organization: saveapis
      project: streamer.bot-cloud
      app: middleware
  template:
    metadata:
      name: middleware
      labels:
        organization: saveapis
        project: streamer.bot-cloud
        app: middleware
    spec:
      containers:
        - name: middleware
          image: registry.digitalocean.com/saveapis/streamer-bot-cloud-middleware:%VERSION%
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: aspnetcore_environment
              valueFrom:
                configMapKeyRef:
                  name: core
                  key: environment
                  optional: false
            - name: Hangfire__Redis__Host
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: host
                  optional: false
            - name: Hangfire__Redis__Port
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: port
                  optional: false
            - name: Hangfire__Redis__UserName
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: username
                  optional: false
            - name: Hangfire__Redis__Password
              valueFrom:
                secretKeyRef:
                  name: valkey
                  key: password
                  optional: false
            - name: Hangfire__Redis__UseSsl
              value: "true"
            - name: Hangfire__Redis__Prefix
              value: "%ENVIRONMENT%:hangfire:middleware:"
            - name: Hangfire__Dashboard__PrefixPath
              value: "/api/middleware"
            - name: MySql__Host
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: host
                  optional: false
            - name: MySql__Port
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: port
                  optional: false
            - name: MySql__UserName
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: username
                  optional: false
            - name: MySql__Password
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
                  optional: false
            - name: MySql__Database
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: middleware-database
                  optional: false
            - name: Encryption__Key
              valueFrom:
                secretKeyRef:
                  name: encryption
                  key: middleware
                  optional: false

            - name: Applications__0__Key
              value: "frontend"
            - name: Applications__0__Name
              value: "Frontend"
            - name: Applications__0__AuthId
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: frontend-auth-id
                  optional: false
            - name: Applications__0__AuthSecret
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: frontend-auth-secret
                  optional: false
            - name: Applications__0__Scopes__0
              value: "application:read"
            - name: Applications__0__Scopes__1
              value: "application:create"
            - name: Applications__0__Scopes__2
              value: "application:update"
            - name: Applications__0__Scopes__3
              value: "application:delete"
            - name: Applications__1__Key
              value: "middleware"
            - name: Applications__1__Name
              value: "Middleware"
            - name: Applications__1__AuthId
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: middleware-auth-id
                  optional: false
            - name: Applications__1__AuthSecret
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: middleware-auth-secret
                  optional: false
            - name: Applications__2__Key
              value: "event-twitch"
            - name: Applications__2__Name
              value: "Event Twitch"
            - name: Applications__2__AuthId
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: event-twitch-auth-id
                  optional: false
            - name: Applications__2__AuthSecret
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: event-twitch-auth-secret
                  optional: false
            - name: Applications__3__Key
              value: "event-discord"
            - name: Applications__3__Name
              value: "Event Discord"
            - name: Applications__3__AuthId
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: event-discord-auth-id
                  optional: false
            - name: Applications__3__AuthSecret
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: event-discord-auth-secret
                  optional: false
            - name: Applications__4__Key
              value: "event-youtube"
            - name: Applications__4__Name
              value: "Event YouTube"
            - name: Applications__4__AuthId
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: event-youtube-auth-id
                  optional: false
            - name: Applications__4__AuthSecret
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: event-youtube-auth-secret
                  optional: false
            - name: Applications__5__Key
              value: "bot-twitch"
            - name: Applications__5__Name
              value: "Bot Twitch"
            - name: Applications__5__AuthId
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: bot-twitch-auth-id
                  optional: false
            - name: Applications__5__AuthSecret
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: bot-twitch-auth-secret
                  optional: false
            - name: Applications__6__Key
              value: "bot-discord"
            - name: Applications__6__Name
              value: "Bot Discord"
            - name: Applications__6__AuthId
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: bot-discord-auth-id
                  optional: false
            - name: Applications__6__AuthSecret
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: bot-discord-auth-secret
                  optional: false
            - name: Applications__7__Key
              value: "bot-youtube"
            - name: Applications__7__Name
              value: "Bot YouTube"
            - name: Applications__7__AuthId
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: bot-youtube-auth-id
                  optional: false
            - name: Applications__7__AuthSecret
              valueFrom:
                secretKeyRef:
                  name: applications
                  key: bot-youtube-auth-secret
                  optional: false

            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: middleware-issuer-audience
                  optional: false
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: middleware-issuer-audience
                  optional: false
            - name: Jwt__SigningKey
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: middleware-signing-key
                  optional: false
            - name: Jwt__ExpirationMinutes
              value: "60"

            - name: Logging__BetterStack__Host
              valueFrom:
                secretKeyRef:
                  name: betterstack
                  key: host
                  optional: false
            - name: Logging__BetterStack__Token
              valueFrom:
                secretKeyRef:
                  name: betterstack
                  key: token
                  optional: false
      restartPolicy: Always
      