name: CD (Production)
on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md

concurrency:
  group: cd-production
  cancel-in-progress: true

jobs:
  read-version:
    outputs:
      version: ${{ steps.read_version.outputs.version }}
    name: Read version
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 9.0.x
      - name: Restore .NET Tools
        run: dotnet tool restore
      - name: Read version
        id: read_version
        run: echo "version=$(dotnet versionize inspect)" >> $GITHUB_OUTPUT
  docker-middleware:
    needs: read-version
    name: Deploy Docker Middleware
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: src/Software/Software.Middleware/Dockerfile
          tags: registry.digitalocean.com/saveapis/streamer-bot-cloud-middleware:${{ needs.read-version.outputs.version }}
          secrets: |
            hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}
            hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}
            hangfire_ace_password=${{ secrets.HANGFIRE_ACE_TOKEN }}
            hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}
            hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}
            hangfire_pro_password=${{ secrets.HANGFIRE_PRO_TOKEN }}
  docker-event-twitch:
    needs: read-version
    name: Deploy Docker Event (Twitch)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: src/Software/Event/Software.Event.Twitch/Dockerfile
          tags: registry.digitalocean.com/saveapis/streamer-bot-cloud-event-twitch:${{ needs.read-version.outputs.version }}
          secrets: |
            hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}
            hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}
            hangfire_ace_password=${{ secrets.HANGFIRE_ACE_TOKEN }}
            hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}
            hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}
            hangfire_pro_password=${{ secrets.HANGFIRE_PRO_TOKEN }}
  docker-event-discord:
    needs: read-version
    name: Deploy Docker Event (Discord)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: src/Software/Event/Software.Event.Discord/Dockerfile
          tags: registry.digitalocean.com/saveapis/streamer-bot-cloud-event-discord:${{ needs.read-version.outputs.version }}
          secrets: |
            hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}
            hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}
            hangfire_ace_password=${{ secrets.HANGFIRE_ACE_TOKEN }}
            hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}
            hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}
            hangfire_pro_password=${{ secrets.HANGFIRE_PRO_TOKEN }}
  docker-event-youtube:
    needs: read-version
    name: Deploy Docker Event (YouTube)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: src/Software/Event/Software.Event.YouTube/Dockerfile
          tags: registry.digitalocean.com/saveapis/streamer-bot-cloud-event-youtube:${{ needs.read-version.outputs.version }}
          secrets: |
            hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}
            hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}
            hangfire_ace_password=${{ secrets.HANGFIRE_ACE_TOKEN }}
            hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}
            hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}
            hangfire_pro_password=${{ secrets.HANGFIRE_PRO_TOKEN }}
  docker-bot-twitch:
    needs: read-version
    name: Deploy Docker Bot (Twitch)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: src/Software/Bot/Software.Bot.Twitch/Dockerfile
          tags: registry.digitalocean.com/saveapis/streamer-bot-cloud-bot-twitch:${{ needs.read-version.outputs.version }}
          secrets: |
            hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}
            hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}
            hangfire_ace_password=${{ secrets.HANGFIRE_ACE_TOKEN }}
            hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}
            hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}
            hangfire_pro_password=${{ secrets.HANGFIRE_PRO_TOKEN }}
  docker-bot-discord:
    needs: read-version
    name: Deploy Docker Bot (Discord)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: src/Software/Bot/Software.Bot.Discord/Dockerfile
          tags: registry.digitalocean.com/saveapis/streamer-bot-cloud-bot-discord:${{ needs.read-version.outputs.version }}
          secrets: |
            hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}
            hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}
            hangfire_ace_password=${{ secrets.HANGFIRE_ACE_TOKEN }}
            hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}
            hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}
            hangfire_pro_password=${{ secrets.HANGFIRE_PRO_TOKEN }}
  docker-bot-youtube:
    needs: read-version
    name: Deploy Docker Bot (YouTube)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: src/Software/Bot/Software.Bot.YouTube/Dockerfile
          tags: registry.digitalocean.com/saveapis/streamer-bot-cloud-bot-youtube:${{ needs.read-version.outputs.version }}
          secrets: |
            hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}
            hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}
            hangfire_ace_password=${{ secrets.HANGFIRE_ACE_TOKEN }}
            hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}
            hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}
            hangfire_pro_password=${{ secrets.HANGFIRE_PRO_TOKEN }}
  kubernetes:
    needs:
      - read-version
      - docker-middleware
      - docker-event-twitch
      - docker-event-discord
      - docker-event-youtube
      - docker-bot-twitch
      - docker-bot-discord
      - docker-bot-youtube
    name: Deploy Kubernetes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Checkout kubernetes config
        run: doctl kubernetes cluster kubeconfig save saveapis
      - name: Replace Variables
        run: |
          find Kubernetes/ -type f -name '*.yaml' -exec sed -i.bak \
            -e 's|%ENVIRONMENT%|production|g' \
            -e 's|%INGRESS_HOST%|streamer-bot-cloud.saveapis.de|g' \
            -e 's|%VALKEY_HOST%|${{ secrets.VALKEY_HOST }}|g' \
            -e 's|%VALKEY_PORT%|${{ secrets.VALKEY_PORT }}|g' \
            -e 's|%VALKEY_USERNAME%|${{ secrets.VALKEY_USERNAME }}|g' \
            -e 's|%VALKEY_PASSWORD%|${{ secrets.VALKEY_PASSWORD }}|g' \
            -e 's|%VERSION%|${{ needs.read-version.outputs.version }}|g' {} +
      - name: Find changed files
        run: find Kubernetes/ -type f -name '*.yaml.bak'
      - name: Deploy to kubernetes
        run: kubectl apply -k Kubernetes/
      - name: Verify Deployment (Middleware)
        run: kubectl rollout status deployment/middleware -n streamer-bot-cloud-production
      - name: Verify Deployment (Event Twitch)
        run: kubectl rollout status deployment/event-twitch -n streamer-bot-cloud-production
      - name: Verify Deployment (Event Discord)
        run: kubectl rollout status deployment/event-discord -n streamer-bot-cloud-production
      - name: Verify Deployment (Event YouTube)
        run: kubectl rollout status deployment/event-youtube -n streamer-bot-cloud-production
      - name: Verify Deployment (Bot Twitch)
        run: kubectl rollout status deployment/bot-twitch -n streamer-bot-cloud-production
      - name: Verify Deployment (Bot Discord)
        run: kubectl rollout status deployment/bot-discord -n streamer-bot-cloud-production
      - name: Verify Deployment (Bot YouTube)
        run: kubectl rollout status deployment/bot-youtube -n streamer-bot-cloud-production